### ISSUE TITLE
Plugin adds <span> tags to blank quiz question choices

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-atto_translations#4]
When creating a multiple choice quiz question, there are 5 choices by default.

Each of these choices is given a <span> tag like:

`<span data-translationhash="df528734035cf75c2c451bb607381755"></span>`

This happens even when the choice is blank.

Meaning that quiz questions are displayed with unwanted blank choices, as shown below:

![image](https://user-images.githubusercontent.com/2512079/175943216-246e84bb-86c0-4d5d-b363-0995726dca3e.png)

Is there any way to avoid this behaviour?

**Comment by andrewhancox** [comment]
Are you running the latest version of the plugin? This is an issue we fixed a while ago.

**Comment by berthelemy** [comment]
We're running plugin version: 2021121311

![image](https://user-images.githubusercontent.com/2512079/176221985-6d3f6b7b-3b38-42ae-9fe0-e790d3291a5b.png)

According to version.php, that's the current version:

`$plugin->version   = 2021121311; `

However, I've just checked, and it looks like the fixed yui files on Github were updated on 18th May after version.php.

We installed the plugin on 9th June. So, in theory, we should have the most recent version.

**Comment by andrewhancox** [comment]
The bug was fixed more recently than the version.php file was updated so that doesn’t actually tell us what’s going on - probably worth upgrading and seeing if that fixes it.
Worth bearing in mind you probably don’t actually need this plugin installed for your use case - you only need this if you’re doing manual translations and want stale manual translations to be used until they get updated.

**Comment by berthelemy** [comment]
Thanks @andrewhancox ,

We installed the plugin after the yui files were updated, but I'll ask for an upgrade.

We will be doing manual translations to fix issues with poor Google translations. Do we still not need the plugin?

**Comment by berthelemy** [comment]
Hi @andrewhancox
We are still finding quiz questions with <span> tags appearing in choices. These are displayed to the user as a blank choice.
We have installed the latest version of the atto_translations plugin.

**Comment by waldonhendricks** [comment]
@andrewhancox i tried adding the plugin via the LMS install method as zipping and I could not do it due to a validation error, should I wait for the plugin to be on Moodle plugins or can I go ahead and add it manually and update my database?

**Comment by andrewhancox** [comment]
The bug was still present in some scenarios. I've just pushed a new fix.
